<?php

namespace App\Filament\Resources;

use App\Filament\Resources\ReadingResource\Pages;
use App\Filament\Resources\ReadingResource\RelationManagers;
use App\Filament\Resources\ReadingsResource\Widgets\Flow;
use App\Models\Reading;
use Filament\Forms;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Form;
use Filament\Forms\Get;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Enums\FiltersLayout;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Facades\Date;

class ReadingResource extends Resource
{

    protected static ?string $model = Reading::class;
    protected static ?string $navigationIcon = 'heroicon-o-adjustments-vertical';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([

            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->poll()
            ->defaultPaginationPageOption(50)
            ->paginationPageOptions([10, 25, 50, 100, 250, 500])
            ->defaultSort('created_at', 'desc')
            ->columns([
                Tables\Columns\TextColumn::make('created_at')
                    ->label('Recorded At')
                    ->dateTime()
                    ->searchable()
                    ->sortable()
                ,
                Tables\Columns\TextColumn::make('source_id')
                    ->label('Source IP')
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make('flow')
                    ->sortable(),
                Tables\Columns\TextColumn::make('accumulative_flow')
                    ->sortable(),
                Tables\Columns\TextColumn::make('status')
                    ->sortable(),
                Tables\Columns\TextColumn::make('pressure')
                    ->sortable(),
                Tables\Columns\TextColumn::make('temperature')
                    ->sortable(),
                Tables\Columns\TextColumn::make('standby')
                    ->sortable(),
            ])
            ->filters([
                Filter::make('date')
                    ->columns()
                    ->columnSpan(2)
                    ->form([
                        Forms\Components\DateTimePicker::make('from')
                            ->default(now()->subWeek()->startOfDay()->toDateTimeString())
                            ->maxDate(fn (Get $get): string => $get('to')),
                        Forms\Components\DateTimePicker::make('to')
                            ->formatStateUsing(fn (string $state): string => Date::parse($state)
                                ->endOfDay()
                                ->toDateTimeString())
                            ->minDate(fn (Get $get): string => $get('from'))
                            ->maxDate(now()->endOfDay())
                            ->default(now()->endOfDay()),
                    ])
                    ->query(
                        static fn (Builder $query, array $data): Builder => $query
                            ->whereBetween('created_at', $data)
                    ),
            ])
            ->filtersLayout(FiltersLayout::AboveContent)
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListReadings::route('/'),
        ];
    }

    public static function canView(Model $record): bool
    {
        return false;
    }

     public static function canEdit(Model $record): bool
    {
        return false;
    }

    public static function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
}
